name: json_viewer
description: "Website that allows you to view json data easily"

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  file_picker: ^8.0.6
  firebase_core: ^3.3.0
  flutter_bloc: ^8.1.6
  flutter_simple_treeview: ^3.0.2
  get_it: ^7.7.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true